export let monster = null;
export const SIZE = 16;
export let money = 2500;
export let food = 1000;
export let population = 0;
export let turn = 0;
export let achievementPoints = 0;
export let tutorialMissions = { '01': false, '02': false, '03': false, '04': false, '05': false, '06': false, '07': false, '08': false };
export let map = [];
export let actionQueue = [];
export let islandName = "MyIsland";
export let warships = [];

export function setMoney(value){ money = value; }
export function changeMoney(value){ money += value; }
export function setFood(value){ food = value; }
export function changeFood(value){ food += value; }
export function setPop(value){ population = value; }
export function setName(value){ islandName = value; }
export function setTurn(value){ turn = value; }
export function setMonster(value){ monster = value; }
